apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weaxle78-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: weaxle78-secrets
    creationPolicy: Owner
  data:
    - secretKey: TWITCH_CLIENT_ID
      remoteRef:
        key: weaxle78
        property: TWITCH_CLIENT_ID
    - secretKey: TWITCH_CLIENT_SECRET
      remoteRef:
        key: weaxle78
        property: TWITCH_CLIENT_SECRET
    - secretKey: TWITCH_LOGIN
      remoteRef:
        key: weaxle78
        property: TWITCH_LOGIN
    - secretKey: YOUTUBE_API_KEY
      remoteRef:
        key: weaxle78
        property: YOUTUBE_API_KEY
    - secretKey: YOUTUBE_CHANNEL_ID
      remoteRef:
        key: weaxle78
        property: YOUTUBE_CHANNEL_ID
    - secretKey: DATABASE_URL
      remoteRef:
        key: weaxle78
        property: DATABASE_URL
