apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weaxle78

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
#  - certificate.yaml
  - httproute.yaml
  - externalsecret.yaml
